### ISSUE TITLE
Compile error when installing package

### ISSUE THREAD

**Issue by weiwei-ww** [christianu7/aistats2020smi#1]
Hi, I recently tried to install your package but encountered the following error.

```
Error: package or namespace load failed for ‘aistats2020smi’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/site-library/00LOCK-aistats2020smi/00new/aistats2020smi/libs/aistats2020smi.so':
  /usr/local/lib/R/site-library/00LOCK-aistats2020smi/00new/aistats2020smi/libs/aistats2020smi.so: undefined symbol: dpotrf_
Error: loading failed
Execution halted
ERROR: loading failed
```

Do you have any idea what might be the cause of this error?

**Comment by chriscarmona** [comment]
Hi @weiwei-ww,

Apologies for the long delay in my response, I've been disconnected from this project in the last few months.
There was indeed a conflict in the package caused by combining C++ code from stan and custom Rcpp Armadillo functions.
I've made significant changes to the general structure in the package and you should be able to install it smoothly with `devtools::install_github("chriscarmona/aistats2020smi")`.

Please let me know if it works for you, or in general if you have any questions about our method.

All the best,
Chris
